backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "jobs"
    label: "Jobs"
    file: "jobs.html"
    fields:
      - { label: "Page Title", name: "title", widget: "string" }
