backend:
  name: github
  repo: deepaksolutionp-maker/Deepak-solution-
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "jobs"
    label: "Latest Jobs"
    folder: "content/jobs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Job Title", name: "title", widget: "string" }
      - { label: "Post Date", name: "date", widget: "datetime" }
      - { label: "Content", name: "body", widget: "markdown" }

  - name: "result"
    label: "Results"
    folder: "content/results"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Result Title", name: "title", widget: "string" }
      - { label: "Result Date", name: "date", widget: "datetime" }
      - { label: "Details", name: "body", widget: "markdown" }

  - name: "admitcard"
    label: "Admit Card"
    folder: "content/admit-card"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Exam Name", name: "title", widget: "string" }
      - { label: "Exam Date", name: "date", widget: "datetime" }
      - { label: "Instructions", name: "body", widget: "markdown" }
